The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

In [4]:
import numpy as np


NumPy Arrays:
1D array 
2D array : axis0, axis1
3D array : axis0, axis1, axis2

Creating Arrays


In [9]:
a=np.array([1,2,3])
b=np.array([(1,2,3), (4,5,6)], dtype=float)
c = np.array([b,b],
dtype = float)
c

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

Initial Placeholders


In [11]:
zeros= np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ones=np.ones((2,3,4),dtype=np.int16)
ones


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [18]:
space=np.linspace(0,2,9)
space


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
f= np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
e = np.full((3,3),5)
e

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [31]:
rand=np.random.random((2,2))
rand

array([[0.44260662, 0.52071244],
       [0.00914796, 0.73709062]])

In [29]:
emp=np.empty((3,3))
emp

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [32]:
np.cos(rand)

array([[0.90363833, 0.86746496],
       [0.99995816, 0.74042719]])

Subsetting, Slicing, Indexing


In [13]:
f=np.eye(4)
f[1:,0]

array([0., 0., 0.])

In [16]:
f[0,0]=5
f

array([[5., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
f[:2,:2]

array([[5., 0.],
       [0., 1.]])

In [20]:
f[:2,0:4]

array([[5., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [22]:
f[0,0]

5.0

In [27]:
arr=np.arange(0,9)
arr.reshape(3,3)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr[[2,2,1,0]]

array([2, 2, 1, 0])

In [32]:
arr=np.random.random((3,3))
arr

array([[0.07035404, 0.78513729, 0.29655489],
       [0.72571858, 0.43521123, 0.7203204 ],
       [0.75490332, 0.79133662, 0.44186141]])

In [37]:

arr[[0,1,2],[0,1,2]]

array([0.07035404, 0.43521123, 0.44186141])